IMAGE_NAME = "bento/ubuntu-18.04"
NR_OF_NODES = 2

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    config.env.enable

    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
    end

    config.vm.define "k8s-master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "192.168.50.10"
        master.vm.hostname = "k8s-master"
        master.vm.synced_folder "../", "/mnt/host"
        master.vm.provision "shell", name: "ca-certificates", path: "../ca-certificates.sh", env: {"CA_CERTIFICATES" => ENV['CA_CERTIFICATES']}

        master.vm.provision "ansible" do |ansible|
            ansible.playbook = "init/master-playbook.yml"
            ansible.host_key_checking = false
            ansible.extra_vars = {
                node_ip: "192.168.50.10"
            }
        end

        config.vm.provision "shell", name: "helm", path: "https://git.io/get_helm.sh"
        config.vm.provision "shell", name: "helm-init", inline: "../helm-init.sh"
        config.vm.provision "shell", name: "nsm", path: "../nsm.sh"
        config.vm.provision "shell", name: "dashboard", path: "../dashboard.sh"
    end

    (1..NR_OF_NODES).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.50.#{i + 10}"
            node.vm.hostname = "node-#{i}"
            node.vm.synced_folder "../", "/mnt/host"
            node.vm.provision "shell", name: "ca-certificates", path: "../ca-certificates.sh", env: {"CA_CERTIFICATES" => ENV['CA_CERTIFICATES']}
            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "init/node-playbook.yml"
                ansible.extra_vars = {
                    node_ip: "192.168.50.#{i + 10}",
                }
            end
        end
    end
end