Vagrant.configure("2") do |config|
  config.env.enable
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.network :forwarded_port, guest: 8080, host: 8080
  config.vm.network :private_network, ip: "192.168.33.10"
  config.vm.network :public_network, :bridge => 'eth1', :use_dhcp_assigned_default_route => true

  config.vm.synced_folder "../../", "/mnt/host"

  config.vm.provider :virtualbox do |v|
      v.memory = 4000
      v.cpus = 2
    end

  config.vm.provision :shell, binary: true, name: "ca-certificates", path: "../scripts/ca-certificates.sh", env: {"CA_CERTIFICATES" => ENV['CA_CERTIFICATES']}
  config.vm.provision :shell, binary: true, name: "docker", path: "../scripts/install-docker.sh"
  config.vm.provision :shell, binary: true, name: "docker-perms", path: "../scripts/docker-addgroup.sh", env: {"USER" => "vagrant"}
  config.vm.provision :shell, binary: true, name: "init", path: "./init.sh"
end
